apiVersion: apps/v1
kind: Deployment
metadata:
  name: subscriptionservice-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: SubscriptionService
  template:
    metadata:
      labels:
        app: SubscriptionService
    spec:
      containers:
      - name: subscriptionservicerepos
        image: sample714cr.azurecr.io/subscriptionservicerepos:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: dsconfigsn

---
apiVersion: v1
kind: Service
metadata:
  name: subscriptionservice
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: SubscriptionService